common:
  prefix: /common
  resource: '@MartenaSoftCommonBundle/Resources/config/routes/all.yaml'
menu:
  prefix: /menu
  resource: '@MartenaSoftMenuBundle/Resources/config/routes/all.yaml'
site:
  resource: '@MartenaSoftSiteBundle/Resources/config/routes/all.yaml'