<?php

namespace App\Tests\unit\Menu\UpDown;

use App\Tests\unit\Menu\AbstractMenuUnit;
use App\Tests\unit\Menu\HelperMenuTrait;
use MartenaSoft\NestedSets\Entity\NodeInterface;

abstract class AbstractMoveUpDown extends AbstractMenuUnit
{
    use HelperMenuTrait;

    protected function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub
        $this->truncateMenuTable();
        $this->initMenu();
    }

    protected ?NodeInterface $firstNode = null;
    protected int $userId = 2;

    public function testRun(): void
    {
        $this->firstNode = $this->getMenuRepository()->find($this->userId);
        $this->moveTo();
        $this->assetItemsArray = $this->getAllNodes();
        $this->moveAsset();
    }

    abstract protected function moveTo(): void;
}